### ISSUE TITLE
improve the output for people without beards and sunglasses

### ISSUE THREAD

**Issue by sradc** [joschuck/matrix-webcam#1]
<img width="655" alt="Screenshot" src="https://user-images.githubusercontent.com/17290057/193475153-06a217ad-d728-4022-966c-31eeb16764ee.png">

(Awesome project 😄; don't take this issue too seriously. (But would appreciate some tips on improving the output, to make it cleaner.))

**Comment by joschuck** [comment]
try to shrink the font size and make the green a bit more desaturated maybe like #4d9807 :sunglasses:
