### ISSUE TITLE
 BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by vorticalbox** [joschuck/matrix-webcam#11]
I am getting the following error in Pop!_os (22.04 LTS) 
```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  4 (X_ShmGetImage)
  Serial number of failed request:  44
  Current serial number in output stream:  44
```

**Comment by joschuck** [comment]
I am using PopOs too, can you provide the command you are using to run the pipeline?

**Comment by vorticalbox** [comment]
> I am using PopOs too, can you provide the command you are using to run the pipeline?

```gst-launch-1.0 ximagesrc xid=121634826 ! video/x-raw,framerate=30/1 ! videoconvert ! video/x-raw,format=YUY2 ! v4l2sink device=/dev/video42```


Weirdly it started working now ill keep an eye on it and see
