### ISSUE TITLE
libGL.so.1 error on WSL Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by thomasbnt** [joschuck/matrix-webcam#5]
Hello ! :wave:
I have just seen your awesome project from [the tweet of GitHub](https://twitter.com/github/status/1577035052004917249) and would like to test that on my WSL Ubuntu 22.04 LTS (on Windows 10), but I've got this error when I run `matrix-webcam` : 

```bash
Traceback (most recent call last):
  File "/home/user/.local/bin/matrix-webcam", line 5, in <module>
    from matrix_webcam.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/matrix_webcam/__main__.py", line 10, in <module>
    import cv2
  File "/home/user/.local/lib/python3.10/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by joschuck** [comment]
thanks for the tweet link, i would have never thought this would happen to this project, haha. I think a quick fix would be 
`$ RUN apt-get update && apt-get install -y python3-opencv`
or 
`$ apt-get install libgl1`

but i should probably move from `opencv-contrib-python` to `opencv-contrib-python-headless` as a dependency for this python package, so this wouldn't be required in the first place

**Comment by thomasbnt** [comment]
Thanks !
