### ISSUE TITLE
Please improve instructions for how to use with OBS

### ISSUE THREAD

**Issue by whyboris** [joschuck/matrix-webcam#6]
I don't have experience with OBS and I've now spent close to an hour trying to get `matrix-webcam` to work with it 😅  (on a Mac)

I have `matrix-webcam` working in the terminal, but other than capturing the window with OBS nothing worked. But also, `matrix-webcam` ends up using the output of the OBS virtual camera, so the video feedback loop prevents me from sharing the entirety of the window. I'm sure I'm doing things "wrong" 😅 

Thank you for your time 🙇 no worries if you don't have time though - I'm just playing with this for fun 👍 😭 👍

**Comment by ksalman** [comment]
I am also running into this thing. When I first ran matrix-webcam it worked as expected but after installing OBS, matrix-webcam seem to be showing the OBS logo (OBS is not even running).

Update: okay I got it working. When starting matrix-webcam, I needed to pick my external webcam `matrix-webcam -d 1`

**Comment by elalemanyo** [comment]
> I am also running into this thing. When I first ran matrix-webcam it worked as expected but after installing OBS, matrix-webcam seem to be showing the OBS logo (OBS is not even running).
> 
> Update: okay I got it working. When starting matrix-webcam, I needed to pick my external webcam `matrix-webcam -d 1`

I can not use `-d` I get this error:
```
usage: matrix-webcam [-h] [width] [height]
matrix-webcam: error: unrecognized arguments: -d
```
I am doing something wrong?
Thanks

**Comment by dconnett-splunk** [comment]
@elalemanyo I ran into this by installing from pip. Try building from source instead. I think it might be an old version in pip.

**Comment by elalemanyo** [comment]
> @elalemanyo I ran into this by installing from pip. Try building from source instead. I think it might be an old version in pip.

@dconnett-splunk Thanks, now works!!! Also thanks to @joschuck! Very nice!

**Comment by eriktelepovsky** [comment]
Can anyone please add step by step instructions how to use it with OBS and Zoom? I can see I can set device using -d parameter, but I am not able to figure it out how to use it in Zoom. When I use OBS Virtual Camera in Zoom settings, I still see regular camera output instead of matrix-webcam. How exactly should be OBS source set up?
