### ISSUE TITLE
Very cool! Is there a font recommendation? My display looks nothing like the preview in the README.

### ISSUE THREAD

**Issue by briantully** [joschuck/matrix-webcam#7]
First off, this is amazing! I initially installed via pip, but the result looked nothing like the animated preview in the README in that I wasn't seeing any falling matrix code. I saw that there was a recent fix for Apple Silicon, so I uninstalled the pip package and cloned the repo and installed the source. That worked a lot better as I was now seeing the falling matrix code behind me.

However I'm wondering if there is a recommended font to use that would make it look more like your preview in the README. I'm currently using iTerm with Meslo LG for Powerline as my font and it doesn't look that great with matrix-webcam. Is there a specific font you would recommend?

**Comment by joschuck** [comment]
I am not sure about fonts, i guess any "hard" monospaced can look decent, also try to desaturate the green a bit, see #1
